title: Simon Winther
description: A blog where I talk about my experience studying Computer Science and also show off some projects or other programming activities off.
theme: just-the-docs
repository: "simonsejse/blog"

url: https://simonsejse.github.io/blog

color_scheme: dark

kramdown: 
  syntax_highlighter_opts:
    block:
      line_numbers: true
 
permalink: pretty

compress_html:
  blanklines: true
  ignore:
    envs: all
mathjax:
  source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
  config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'

collections:
  programming:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    programming:
      name: Programming with

callouts_level: loud

callouts:
  admonition:
    # title:
    color: grey-lt
  attention:
    title: Attention
    color: purple
  caution:
    title: Caution
    color: yellow
  danger:
    title: Danger
    color: red
  error:
    title: Error
    color: red
  highlight:
    color: yellow
    opacity: 0.5
  hint:
    title: Hint
    color: grey-dk
  important:
    title: Important
    color: green
  note:
    title: Note
    color: blue
  #   color: pink
  #   opacity: 0.3
  tip:
    title: Tip
    color: grey-dk
  warning:
    title: Warning
    color: red
  console:
    title: Console output
    color: pink
